# Generated by Django 3.2.12 on 2022-02-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
