# Generated by Django 3.2.12 on 2022-02-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_enabled'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='note_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='note.note'),
            preserve_default=False,
        ),
    ]
